name: gifx
description: A gif library, you can control the gif play and pause, you can set the gif playback time and thus control the frame rate.
version: 1.0.0
homepage: https://github.com/haishuangsu/gifx.git

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

